### PR TITLE
Wrong Test

### PR DESCRIPTION
**Pull request by LarsKumbier**
The resulting graph contains two squares, not one
- Pos: 1, Size: 1
- Pos: 1, Size: 5

### CODE REVIEW

**Comment by Bryukh** [comment]
You are wrong. Please read the description more careful.

**Comment by LarsKumbier** [comment]
According to the rank 3 description, _Some points can be destroyed. If you see (0, N) or (N, 0), then N-th points is destroyed and all lines with this point are wiped out too._

To my understanding, this should happen _immediately_, when a point definition is met - so when the input `[19, 0]` is handled, the two connections to `20` and `24` are destroyed. But when the input `[0, 10]` is handled, no connections are destroyed, because all connections to `10` are done later.

If the point deletion should happen at the _end_ of the whole process, that's a different story. In that case, I'd suggest changing the problem description.

**Comment by Bryukh** [comment]
If a point is destroyed, then it's cann't be connected and all lines with this point connect nothing.

**Comment by LarsKumbier** [comment]
Ok, misunderstood the concept then. I merely created points on the fly, so for me, if a point is destroyed at some point in the process and the input instructs a new connection, I rebuild the point.

Maybe an update to the description would help in the future.

**Pull request closed without merging**
